# Run unit tests

name: .NET unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: 'true'
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Test
      run: dotnet test tests/tests.csproj --verbosity normal
    - name: Publish
      run: |
        cd clitool
        dotnet publish -o out --configuration Release -r linux-x64
